name: Feature request
description: Suggest an idea or improvement for SK Image.
labels: ['enhancement']
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Your idea
      description: What would you like SK Image to do?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
